language: groovy

jdk:
  - oraclejdk8

sudo: false

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.m2/


before_script:
 - rm -rf .grails


script: "./travis-build.sh"
