# see defaults options https://github.com/yakworks/gradle-plugins/tree/master/src/main/resources/configs/defaults.yml
title: AuditTrail
description: Audit Trail Grails Plugin
author: Yak.Works
group: org.grails.plugins

github:
  fullName: 9ci/grails-audit-trail

team:
  developers: ['basejump: Joshua Burnett']

bintray:
  enabled: true
  # user: ${findAnyProperty("BINTRAY_USER")} //uses System var property
  # key: ${props.findAny("BINTRAY_KEY")} //uses System var property
  pkg:
    repo: grails-plugins
    userOrg: 9ci

maven:
  # repoUrl: http://repo.9ci.com/grails-plugins
  snapshotUrl: http://repo.9ci.com/oss-snapshots
